#
# Makefile
# Jim Zenn, 2019-01-18 08:23
#

CC=clang++

Set:
	$(CC) Set.cpp testSet.cpp -Wall -Wextra -o testSet && ./testSet

newSet:
	$(CC) newSet.cpp testNewSet.cpp -Wall -Wextra -o testNewSet && ./testNewSet

SSNSet:
	$(CC) Set.cpp SSNSet.cpp testSSNSet.cpp -Wall -Wextra -o testSSNSet && ./testSSNSet

newSSNset:
	$(CC) newSet.cpp SSNSet.cpp testSSNSet.cpp -Wall -Wextra -o testSSNSet && ./testSSNSet


# vim:ft=make
#
