#
# Makefile
# Jim Zenn, 2019-01-18 08:23
#

CC=clang++

Set:
	$(CC) testSet.cpp Set.cpp -Wall -Wextra -o testSet && ./testSet

newSet:
	$(CC) testnewSet.cpp newSet.cpp -Wall -Wextra -o testnewSet && ./testnewSet

SSNSet:
	$(CC) testSSNSet.cpp Set.cpp SSNSet.cpp -Wall -Wextra -o testSSNSet && ./testSSNSet

newSSNSet:
	$(CC) testSSNSet.cpp newSet.cpp SSNSet.cpp -Wall -Wextra -o testSSNSet && ./testSSNSet


# vim:ft=make
#
