#
# Makefile
# Jim Zenn, 2019-01-18 08:23
#

CC=clang++

Set:
	$(CC) Set.cpp testSet.cpp -Wall -Wextra -o testSet && ./testSet

SSNset:
	$(CC) Set.cpp SSNSet.cpp testSSNSet.cpp -Wall -Wextra -o testSSNSet && ./testSSNSet


# vim:ft=make
#
